#≈‰÷√Œƒº˛
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1314520
    username: root
    url: jdbc:mysql://localhost:3306/bookInfo?serverTimezone=UTC
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 80
  servlet:
    session:
      timeout: 300s